/* ============================================================
   Teclatlon — Texts (EN)
   Language-specific file. Loaded conditionally from index.html
   depending on App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "⌨️ Teclatlon",
    "textoNombre": "Hi! What is your name? Type your name on the keyboard.",
    "escucharNombreExtra": " When you are done, tap the Done button.",
    "inputNombreAria": "Type your name",
    "btnGuardarNombre": "✅ Done",
    "btnSinNombre": "Not now",
    "tipoTecladoAria": "Keyboard type",
    "btnSimple": "🔤 Simple",
    "btnNormal": "⌨️ Normal",
    "btnExtendido": "🔢 Extended",
    "btnColoresManos": "🎨 Colors: hands",
    "btnColoresDedos": "🎨 Colors: fingers",
    "leyendaDedos": "Each finger has its own color.",
    "leyendaManos": "Blue: left hand. Green: right hand.",
    "btnBorrarProgreso": "🗑️ Erase my progress",
    "confirmarBorrado": "Are you sure? Tap again to erase.",
    "avisoBorrado": "Everything erased. You start again.",
    "saludoHola": "Hi!",
    "saludoConNombre": "Hi, {nombre}!",
    "eligeJuego": "Choose a game.",
    "modoPosicionNombre": "Place your fingers",
    "modoPosicionDetalle": "Each finger has its key.",
    "modoLeccionesNombre": "Step by step",
    "modoLeccionesDetalle": "Learn the letters in order.",
    "modoPalabrasNombre": "Words",
    "modoPalabrasDetalle": "Type words and your name.",
    "modoTodasNombre": "All the keys",
    "modoTodasDetalle": "Light up every key.",
    "modoNumerosNombre": "Numbers",
    "modoNumerosDetalle": "Use the number pad.",
    "modoLibreNombre": "Free writing",
    "modoLibreDetalle": "Type and listen to your text.",
    "btnMiNombre": "✏️ My name",
    "btnMenu": "← Menu",
    "leccionesInstruccion": "Finish a lesson to unlock the next one.",
    "leccionCerradaAria": "Lesson {n} locked. Finish the previous one.",
    "tituloJuegoDefault": "Game",
    "escucharTextoAria": "Listen to my text",
    "borrarTextoAria": "Erase the text",
    "areaLibreAria": "Type anything you like here",
    "areaLibrePlaceholder": "Type here...",
    "noHasEscrito": "You have not written anything yet.",
    "muyBien": "Well done!",
    "muyBienNombre": "Well done, {nombre}!",
    "escribeTuNombre": "Type your name.",
    "escribeLaPalabra": "Type the word.",
    "tituloTodasLasTeclas": "All the keys",
    "instruccionTodasLasTeclas": "Press every key on your keyboard. Each key lights up on the screen.",
    "deTexto": "{hechas} of {total}",
    "escribeAria": "Type: {seq}",
    "pulgarTexto": "Thumb. The space bar.",
    "manoDedoTexto": "{mano} hand. {dedo} finger.",
    "buscaTecla": "Find the key on your keyboard.",
    "leccionTitulo": "Lesson: {titulo}",
    "izquierdaEtiqueta": "Left",
    "derechaEtiqueta": "Right",
    "dedo": {"lp":{"mano":"left","nombre":"little"},"lr":{"mano":"left","nombre":"ring"},"lm":{"mano":"left","nombre":"middle"},"li":{"mano":"left","nombre":"index"},"ri":{"mano":"right","nombre":"index"},"rm":{"mano":"right","nombre":"middle"},"rr":{"mano":"right","nombre":"ring"},"rp":{"mano":"right","nombre":"little"},"th":{"mano":"both","nombre":"thumb"}},
    "teclaLabel": {"espacio":"space","tab":"Tab","mayus":"Shift","intro":"Enter","borrar":"Backspace"},
    "transferencia": "This helps you write real messages to family on the computer."
  }, 'en');
})();
