/* ============================================================
   Teclatlon — Texts (ES)
   Language-specific file. Loaded conditionally from index.html
   depending on App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "⌨️ Teclatlon",
    "nameScreenText": "¡Hola! ¿Cómo te llamas? Escribe tu nombre con el teclado.",
    "listenNameExtra": " Cuando termines, toca el botón Listo.",
    "nameInputAria": "Escribe tu nombre",
    "btnSaveName": "✅ Listo",
    "btnSkipName": "Ahora no",
    "keyboardViewAria": "Vista del teclado",
    "btnSimple": "🔤 Solo letras",
    "btnNormal": "⌨️ Letras y números",
    "btnExtended": "🔢 Con números al lado",
    "btnSimpleDetail": "Solo se ven las letras. Es lo más sencillo.",
    "btnNormalDetail": "Se ven las letras y los números, como un teclado normal.",
    "btnExtendedDetail": "Se ve todo el teclado y, además, los números a la derecha.",
    "btnColorsHands": "🎨 Colores: manos",
    "btnColorsFingers": "🎨 Colores: dedos",
    "legendFingers": "Cada dedo tiene un color.",
    "legendHands": "Azul: mano izquierda. Verde: mano derecha.",
    "btnClearProgress": "🗑️ Borrar mi progreso",
    "confirmClear": "¿Seguro? Toca otra vez para borrar.",
    "clearedNotice": "Todo borrado. Empiezas de nuevo.",
    "greetingHello": "¡Hola!",
    "greetingWithName": "¡Hola, {name}!",
    "chooseGame": "Elige un juego.",
    "modePlacementName": "Coloca los dedos",
    "modePlacementDetail": "Cada dedo tiene su tecla.",
    "modeLessonsName": "Paso a paso",
    "modeLessonsDetail": "Aprende las letras en orden.",
    "modeWordsName": "Palabras",
    "modeWordsDetail": "Escribe palabras y tu nombre.",
    "modeAllKeysName": "Todas las teclas",
    "modeAllKeysDetail": "Enciende todas las teclas.",
    "modeNumbersName": "Números",
    "modeNumbersDetail": "Usa el teclado de números.",
    "modeFreeName": "Escribe libre",
    "modeFreeDetail": "Escribe y escucha tu texto.",
    "modeTemplatesName": "Textos reales",
    "modeTemplatesDetail": "Practica con un correo o una carta.",
    "btnMyName": "✏️ Mi nombre",
    "btnMenu": "← Menú",
    "lessonsInstruction": "Termina una lección para abrir la siguiente.",
    "lessonLockedAria": "Lección {n} cerrada. Termina la anterior.",
    "templatesInstruction": "Elige un texto para practicar.",
    "templateInstruction": "Escribe la siguiente línea.",
    "gameTitleDefault": "Juego",
    "listenTextAria": "Escuchar mi texto",
    "clearTextAria": "Borrar el texto",
    "freeAreaAria": "Escribe aquí lo que quieras",
    "freeAreaPlaceholder": "Escribe aquí...",
    "nothingWrittenYet": "Todavía no has escrito nada.",
    "wellDone": "¡Muy bien!",
    "wellDoneWithName": "¡Muy bien, {name}!",
    "typeYourName": "Escribe tu nombre.",
    "typeTheWord": "Escribe la palabra.",
    "allKeysTitle": "Todas las teclas",
    "allKeysInstruction": "Pulsa todas las teclas de tu teclado. Cada tecla se enciende en la pantalla.",
    "challengeNextKey": "Pulsa la tecla {key} con el dedo {finger} de la mano {hand}.",
    "challengeNextKeyThumb": "Pulsa la tecla {key} con el pulgar.",
    "doneOfTotal": "{done} de {total}",
    "typeAria": "Escribe: {seq}",
    "pressKeyAria": "Pulsa: {key}",
    "thumbText": "Pulgar. La tecla de espacio.",
    "handFingerText": "Mano {hand}. Dedo {finger}.",
    "shiftText": "También mantén pulsada Mayús con el meñique de la mano {hand}.",
    "findKey": "Busca la tecla en tu teclado.",
    "lessonTitle": "Lección: {title}",
    "lessonReview": "Repaso: pulsa todas las teclas que has aprendido hasta ahora, en el orden del teclado.",
    "leftLabel": "Izquierda",
    "rightLabel": "Derecha",
    "finger": {"lp":{"hand":"izquierda","name":"meñique"},"lr":{"hand":"izquierda","name":"anular"},"lm":{"hand":"izquierda","name":"medio"},"li":{"hand":"izquierda","name":"índice"},"ri":{"hand":"derecha","name":"índice"},"rm":{"hand":"derecha","name":"medio"},"rr":{"hand":"derecha","name":"anular"},"rp":{"hand":"derecha","name":"meñique"},"th":{"hand":"las dos","name":"pulgar"}},
    "keyLabel": {"space":"espacio","tab":"Tab","shift":"Mayús","enter":"Intro","backspace":"Borrar","home":"Inicio","end":"Fin","pageUp":"Re Pág","pageDown":"Av Pág","delete":"Supr"},
    "transferMessage": "Esto te ayuda a escribir mensajes reales a la familia en el ordenador.",
    "languageLabel": "🌐 Idioma",
    "languageLabelAria": "Elegir idioma",
    "focusModeLabel": "🧘 Sin distracciones",
    "focusModeLabelAria": "Activar o desactivar el modo sin distracciones",
    "focusModeLabelOn": "✅ Sin distracciones: activado",
    "focusModeLabelOff": "⬜ Sin distracciones: desactivado",
    "textSizeA": "A−",
    "textSizeAria": "Tamaño del texto",
    "textSizeAdjustAria": "Aumentar o reducir el tamaño del texto",
    "themeLabel": "🌗 Tema",
    "themeLabelAria": "Cambiar el tema claro, oscuro o alto contraste",
    "themeLabelAuto": "Tema: automático",
    "themeLabelLight": "Tema: claro",
    "themeLabelDark": "Tema: oscuro",
    "themeLabelContrast": "Tema: alto contraste",

    /* Métricas: el producto no ha cerrado los detalles pero el botón
       se queda visible (y apagado por defecto) para que la persona
       usuaria lo encuentre y entienda que existe. La implementación
       actual muestra precisión (%) y teclas por minuto en vivo. */
    "metricsLabel": "📊 Métricas",
    "metricsLabelAria": "Activar o desactivar las métricas de precisión y velocidad",
    "metricsLabelOn": "✅ Métricas: encendidas",
    "metricsLabelOff": "⬜ Métricas: apagadas",

    /* Sonido espacial: el tono de acierto suena por el lado (izquierda
       o derecha) de la tecla pulsada, para reforzar la posición de la
       mano sin depender de la vista. */
    "spatialSoundLabel": "🎧 Sonido espacial",
    "spatialSoundLabelAria": "Activar o desactivar el sonido espacial",
    "spatialSoundLabelOn": "✅ Sonido espacial: encendido",
    "spatialSoundLabelOff": "⬜ Sonido espacial: apagado",

    "accuracy": "Precisión: {n}%",
    "accuracyShort": "Prec. {n}%",
    "keysPerMinute": "PPM: {n}",
    "keysPerMinuteShort": "{n} PPM",
    "keysLabel": "Teclas: {n}",
    "timeShort": "{n}s",

    "openSettingsAria": "Abrir ajustes",
    "closeSettingsAria": "Cerrar ajustes",
    "settingsHeader": "Ajustes",
    "settingsPanel": "Ajustes de accesibilidad y juego",
    "settingsHelp": "Estos ajustes se guardan en este dispositivo.",
    "computerOnly": "Solo en el ordenador",
    "computerOnlyWhy": "Teclatlon es para practicar mecanografía con el teclado del ordenador.",
    "computerOnlyReason": "Necesitamos el teclado físico para escribir a máquina. El teclado que ves dibujado en pantalla no se puede pulsar. En un móvil o tablet no hay teclas de verdad para practicar.",
    "computerOnlySuggestion": "Abre esta página desde un portátil o un PC. Si tu móvil tiene un teclado físico, conéctalo por Bluetooth o USB.",

    /* --- /legal (Protección de datos) ----------------------------------
       Antes vivían en legal/strings.es.js. Consolidado en el dict raíz
       tras fusionar /legal en index.html (SPA). El HTML dentro de
       #view-legal usa data-i18n="legal.<key>"; el prefijo es obligatorio
       para no colisionar con strings planos del mismo nombre. */
    legal: {
      pageTitle: 'Protección de datos',
      tagline: 'Sin registro. Sin cookies. Sin analítica.',
      lead: 'Teclatlon no pide tus datos personales. Todo lo que guarda vive únicamente en este dispositivo. Aquí explicamos, en detalle, qué guardamos y por qué.',
      navResponsible: 'Quién trata tus datos',
      navData: 'Qué guardamos',
      navRights: 'Tus derechos',
      navMinors: 'Todas las edades',
      navContact: 'Cambios y contacto',
      responsibleTitle: 'Quién trata tus datos',
      responsibleP1a: 'Teclatlon es una iniciativa de ',
      responsibleP1b: ', un estudio independiente que desarrolla y mantiene la aplicación. No hay ningún servidor propio que reciba o almacene tus datos: la aplicación es un conjunto de páginas estáticas que se ejecutan en tu navegador.',
      responsibleP2a: 'El código fuente completo es público y auditable en el ',
      responsibleP2Link: 'repositorio de GitHub',
      responsibleP2b: '. Cualquier pregunta sobre esta página puede plantearse abriendo un issue allí.',
      dataTitle: 'Qué guardamos y por qué',
      dataP1: 'Teclatlon funciona sin cuentas, sin cookies y sin analítica: no sabemos quién eres ni cómo usas la aplicación.',
      dataP2: 'Lo único que se guarda vive en el localStorage de tu navegador, en tu propio dispositivo, y nunca se envía a ningún servidor:',
      dataItem1Label: 'Progreso del juego',
      dataItem1Text: 'las estrellas ganadas, las lecciones completadas, las insignias conseguidas y tu mejor racha de teclas correctas.',
      dataItem2Label: 'Idioma elegido',
      dataItem2Text: 'para no tener que elegirlo de nuevo cada vez que abres la aplicación.',
      dataItem3Label: 'Ajustes de accesibilidad y juego',
      dataItem3Text: 'tamaño del texto, tema, modo foco, lectura fácil y otros ajustes del panel.',
      dataP3: 'Nunca guardamos: nombre, contraseñas, texto libre escrito, identificadores personales únicos, fallos, tiempo empleado, número de intentos, comparaciones con otras personas ni historiales de uso detallados.',
      dataP4: 'Esta información se guarda mientras no se borre, y sirve únicamente para que el progreso no se pierda al cerrar la aplicación.',
      rightsTitle: 'Tus derechos y cómo ejercerlos',
      rightsP1: 'Como todo lo guardado está en tu dispositivo y no en un servidor, tú tienes el control directo: puedes verlo, cambiarlo o borrarlo en cualquier momento, sin pedírnoslo a nosotros.',
      rightsP2: 'Para borrarlo, usa el botón "Borrar mi progreso" que aparece en la propia aplicación, o bien borra los datos de navegación de tu navegador para este sitio, desde su configuración.',
      rightsLinkApp: 'Ir a Teclatlon',
      minorsTitle: 'Todas las edades y capacidades',
      minorsP1: 'Teclatlon está pensada para que la use de forma autónoma cualquier persona, sin importar su edad ni sus capacidades, incluidos quienes están empezando a usar el teclado físico por primera vez.',
      minorsP2: 'Como la aplicación no recoge datos personales en ningún servidor, no es necesario el consentimiento de nadie para tratar datos: no hay ningún tratamiento que autorizar. Sí recomendamos la supervisión habitual que una familia o un profesional haga sobre el uso de cualquier dispositivo.',
      contactTitle: 'Cambios y contacto',
      contactP1: 'Esta página puede actualizarse si cambia la aplicación. El historial de cambios es público en el repositorio de GitHub.',
      contactP2: 'Última actualización: 30 de agosto de 2026.',
      contactP3a: 'Para preguntas sobre esta página, abre un issue en el ',
      contactP3Link: 'repositorio de GitHub',
      contactP3b: '.',
      footerActivities: 'Ir a la aplicación'
    },

    /* --- /about (Presentación del proyecto) ----------------------------
       Antes vivían en about/strings.es.js. Hoy son vistas SPA dentro de
       index.html (#view-about) accesibles por URL directa, pero con
       hidden routes (noindex, nofollow). */
    about: {
      pageTitle: 'Presentación del proyecto',
      routeNotice: 'Esta página no se enlaza desde la aplicación. Solo se llega escribiendo la dirección.',
      tagline: 'Una aplicación para la autonomía.',
      lead1: 'Teclatlon es una ',
      leadStrong: 'aplicación web de mecanografía con teclado físico',
      lead2: ' pensada para que cualquier persona, con o sin experiencia previa, aprenda a escribir con los diez dedos, sin presión y con respeto a su privacidad.',
      navOrigin: 'El origen',
      navPrinciples: 'Los principios',
      navTech: 'Cómo está hecha',
      navAreas: 'Las áreas de trabajo',
      navSiblings: 'Proyectos hermanos',
      navAuthorship: 'Quiénes la hacen',
      navCollaborate: 'Cómo ayudar',
      originTitle: 'El origen',
      originP1a: 'Teclatlon nace de una pregunta que se repite al final de cada sesión de apoyo al aprendizaje: ',
      originP1em: '¿qué pasa entre una sesión y la siguiente?',
      originP2: 'La persona usuaria practica con quien le acompaña en consulta o en casa, pero después está sola en casa, en el colegio o en su tiempo libre. Queríamos una herramienta que respetase esa autonomía, que diese seguridad a las familias y que sirviese a quien acompaña como complemento entre sesiones, no como sustituto.',
      originP3: 'Esta aplicación es el resultado: una sola herramienta de mecanografía, con varios modos de teclado y por colores por dedo, en Lectura Fácil y accesible, pensada para que la persona usuaria pueda practicar a su propio ritmo.',
      principlesTitle: 'Los principios que no negociamos',
      principlesIntro: 'Estas ideas están escritas primero en el código y después en los textos. Si una decisión las rompe, esa decisión está mal.',
      principleAutonomyTitle: '🤲 Autonomía real',
      principleAutonomyText: 'La persona usuaria puede usar la aplicación sin un profesional al lado. Si necesita ayuda constante, algo no está bien resuelto.',
      principleNoPressureTitle: '🚫 Sin presión',
      principleNoPressureText: 'Nada de cronómetros, ni "game over", ni puntuaciones negativas. El error se responde con ánimo y se puede reintentar sin límite.',
      principlePrivacyTitle: '🔒 Privacidad por defecto',
      principlePrivacyText: 'Sin registro, sin cookies, sin analítica, sin cuentas. Todo el progreso se guarda únicamente en el dispositivo de la persona.',
      principleEasyReadTitle: '📖 Lectura Fácil',
      principleEasyReadText: 'Frases cortas, una idea por frase, vocabulario cotidiano. Cero tecnicismos en la interfaz que ve la persona usuaria.',
      principleAccessibilityTitle: '♿ Accesibilidad universal',
      principleAccessibilityText: 'Teclado físico de gran tamaño con teclas de color por dedo, alto contraste, audio solo cuando la gamificación o el diseño de la actividad lo requiera (p. ej. escuchar la letra a escribir), navegación completa por teclado, y respeto al modo de pocas animaciones del sistema.',
      principleSoberTechTitle: '🧱 Tecnología sobria',
      principleSoberTechText: 'HTML, CSS y JavaScript sin frameworks. Funciona sin internet y se puede instalar como aplicación. Código abierto, en un repositorio público.',
      techTitle: 'Cómo está hecha',
      techIntro1: 'Teclatlon es una aplicación web instalable (PWA) compuesta por más de ',
      techIntroStrong: '5 páginas HTML estáticas',
      techIntro2: ': la landing, el teclado virtual y rutas ocultas para familias, profesionales y mantenimiento.',
      techItem1Label: 'Sin servidor propio',
      techItem1Text: 'es un conjunto de archivos servidos por un hosting estático. No hay backend, ni bases de datos, ni API propia.',
      techItem2Label: 'Funciona sin conexión',
      techItem2Text: 'una vez instalada, abre aunque no haya internet gracias al service worker y al caché local.',
      techItem3Label: 'Persistencia solo en',
      techItem3Text: 'el progreso (estrellas, letras practicadas, modo de teclado elegido) vive en el navegador del dispositivo. Nunca se envía a ningún sitio.',
      techItem4Label: 'Sin frameworks ni build step',
      techItem4Text1: 'JavaScript clásico compatible con navegadores antiguos y con el protocolo',
      techItem4Text2: '. Pensado para que un técnico novel pueda leer y modificar una lección sin sorpresas.',
      techItem5Label: 'Código abierto (licencia MIT)',
      techItem5Text: 'cualquiera puede leerlo, auditarlo y proponer mejoras. Las decisiones de producto están escritas en este repositorio, no en presentaciones cerradas.',
      techItem6Label: 'Internacionalización desde el inicio',
      techItem6Text: 'cada texto vive en un archivo por idioma. Hoy Teclatlon está disponible en español de España e inglés.',
      techItem7Label: 'Dependencias externas: ninguna',
      techItem7Text: ', excepto la descarga de las fuentes tipográficas Atkinson Hyperlegible y Nunito (usadas por su alta legibilidad).',
      areasTitle: 'Las áreas de trabajo',
      areasIntro1: 'Una sola herramienta, pero la mecanografía se organiza en ',
      areasIntroStrong: 'seis bloques por mano y dedo',
      areasIntro2: ', cada uno con su color identificativo en el teclado virtual. Cada lección trabaja un bloque, y la persona avanza a su ritmo: puede empezar por el índice y subir hasta escribir con los diez dedos.',
      areaLeftHandTitle: '✋ Mano izquierda',
      areaLeftHandText: 'Las cinco teclas que se escriben con la mano izquierda (y los pulgares para el espacio).',
      areaLeftHandCount: '5 teclas',
      areaRightHandTitle: '🤚 Mano derecha',
      areaRightHandText: 'Las cinco teclas que se escriben con la mano derecha.',
      areaRightHandCount: '5 teclas',
      areaRingFingerTitle: '💍 Dedo anular',
      areaRingFingerText: 'Las teclas que pulsan los dedos anulares (uno en cada mano).',
      areaRingFingerCount: '2 teclas',
      areaMiddleFingerTitle: '🖕 Dedo corazón',
      areaMiddleFingerText: 'Las teclas que pulsan los dedos corazón (uno en cada mano).',
      areaMiddleFingerCount: '2 teclas',
      areaPinkyTitle: '🤞 Meñique',
      areaPinkyText: 'Las teclas que pulsan los meñiques (uno en cada mano).',
      areaPinkyCount: '2 teclas',
      areaModesTitle: '🎹 Modos de teclado',
      areaModesText: 'Teclado simple, normal, extendido y con colores por dedo.',
      areaModesCount: '4 modos',
      areasNote1: 'Total: ',
      areasNoteStrong: '1 herramienta, varias lecciones',
      areasNote2: ', organizadas para que la persona elija por interés, no por obligación. El orden del menú no es un itinerario: cada persona hace su propio camino.',
      siblingsTitle: 'Proyectos hermanos',
      siblingsIntro: 'Teclatlon es uno más de un pequeño grupo de proyectos hermanos: mismo equipo, misma filosofía de accesibilidad y sin servidor propio. Cada uno es un servicio independiente, con su propio dominio, al que se puede llegar desde aquí.',
      siblingRoutimeName: 'Routime',
      siblingRoutimeText: 'Rutinas y autonomía del día a día.',
      siblingCalculiaName: 'Calculia',
      siblingCalculiaText: 'Cálculo y razonamiento lógico.',
      siblingMemofunName: 'Memofun',
      siblingMemofunText: 'Memoria y atención.',
      siblingOkeymoneyName: 'Okeymoney',
      siblingOkeymoneyText: 'Finanzas personales y autonomía cotidiana.',
      siblingSinonimiaName: 'Sinonimia',
      siblingSinonimiaText: 'Diccionario en lectura fácil.',
      siblingLinkHint: 'Se abre en una pestaña nueva.',
      authorshipTitle: 'Quiénes la hacen',
      authorshipP1a: 'Teclatlon es una iniciativa de ',
      authorshipP1b: ', un estudio independiente que trabaja en proyectos abiertos con impacto social y educativo.',
      authorshipP2: 'La aplicación se construye con la participación de personas con perfiles de aprendizaje diversos, familias, profesionales de apoyo y profesorado, que prueban cada cambio y revisan el contenido antes de que llegue a producción.',
      authorshipP3: 'El código, el texto y las decisiones se publican en abierto para que cualquier persona o equipo pueda auditarlos, aprender de ellos y adaptarlos a otros contextos.',
      collaborateTitle: 'Cómo ayudar',
      collaborateIntro: 'Teclatlon es un proyecto abierto. Hay formas de colaborar que no requieren programar:',
      collaborateItem1Label: 'Probar y compartir feedback',
      collaborateItem1Text: 'las familias, terapeutas y personas usuarias que prueban la aplicación y cuentan qué funciona y qué no, son la pieza clave del proyecto. Los errores de Lectura Fácil, los tonos poco amables y las lecciones que cuesta entender se detectan usándolas.',
      collaborateItem2Label: 'Proponer lecciones',
      collaborateItem2Text: 'si una habilidad de mecanografía no está cubierta o se trabaja de una forma mejorable, se puede proponer una lección nueva. La descripción didáctica la valida un profesional antes de pasar a código.',
      collaborateItem3Label: 'Revisar contenido',
      collaborateItem3Text: 'traducciones, ejemplos culturalmente adecuados, explicaciones accesibles. La interfaz que ve la persona usuaria es en Lectura Fácil y se beneficia especialmente de ojos ajenos.',
      collaborateItem4Label: 'Contribuir código',
      collaborateItem4Text: 'el repositorio es público. Cambios pequeños (un icono, una traducción, una corrección de estilo) y grandes (lecciones nuevas, accesibilidad, soporte para más idiomas) se aceptan siempre que respeten los principios del proyecto.',
      collaborateItem5Label: 'Difundir',
      collaborateItem5Text: 'contar que existe. Muchas familias, profesionales y centros no saben que hay herramientas como esta hasta que alguien se la enseña.',
      collaborateOutro1: 'Toda la documentación necesaria para empezar está en los archivos',
      collaborateOutro3: 'y',
      collaborateOutro4: 'del repositorio.',
      footerActivities: 'Ir a la aplicación'
    }
  }, 'es');
})();
