/* ============================================================
   Teclatlon — Textos (ES)
   Archivo específico del idioma. Se carga condicionalmente desde
   index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "⌨️ Teclatlon",
    "textoNombre": "¡Hola! ¿Cómo te llamas? Escribe tu nombre con el teclado.",
    "escucharNombreExtra": " Cuando termines, toca el botón Listo.",
    "inputNombreAria": "Escribe tu nombre",
    "btnGuardarNombre": "✅ Listo",
    "btnSinNombre": "Ahora no",
    "tipoTecladoAria": "Vista del teclado",
    "btnSimple": "🔤 Solo letras",
    "btnNormal": "⌨️ Letras y números",
    "btnExtendido": "🔢 Con números al lado",
    "btnSimpleDetalle": "Solo se ven las letras. Es lo más sencillo.",
    "btnNormalDetalle": "Se ven las letras y los números, como un teclado normal.",
    "btnExtendidoDetalle": "Se ve todo el teclado y, además, los números a la derecha.",
    "btnColoresManos": "🎨 Colores: manos",
    "btnColoresDedos": "🎨 Colores: dedos",
    "leyendaDedos": "Cada dedo tiene un color.",
    "leyendaManos": "Azul: mano izquierda. Verde: mano derecha.",
    "btnBorrarProgreso": "🗑️ Borrar mi progreso",
    "confirmarBorrado": "¿Seguro? Toca otra vez para borrar.",
    "avisoBorrado": "Todo borrado. Empiezas de nuevo.",
    "saludoHola": "¡Hola!",
    "saludoConNombre": "¡Hola, {nombre}!",
    "eligeJuego": "Elige un juego.",
    "modoPosicionNombre": "Coloca los dedos",
    "modoPosicionDetalle": "Cada dedo tiene su tecla.",
    "modoLeccionesNombre": "Paso a paso",
    "modoLeccionesDetalle": "Aprende las letras en orden.",
    "modoPalabrasNombre": "Palabras",
    "modoPalabrasDetalle": "Escribe palabras y tu nombre.",
    "modoTodasNombre": "Todas las teclas",
    "modoTodasDetalle": "Enciende todas las teclas.",
    "modoNumerosNombre": "Números",
    "modoNumerosDetalle": "Usa el teclado de números.",
    "modoLibreNombre": "Escribe libre",
    "modoLibreDetalle": "Escribe y escucha tu texto.",
    "modoPlantillasNombre": "Textos reales",
    "modoPlantillasDetalle": "Practica con un correo o una carta.",
    "btnMiNombre": "✏️ Mi nombre",
    "btnMenu": "← Menú",
    "leccionesInstruccion": "Termina una lección para abrir la siguiente.",
    "leccionCerradaAria": "Lección {n} cerrada. Termina la anterior.",
    "plantillasInstruccion": "Elige un texto para practicar.",
    "plantillaInstruccion": "Escribe la siguiente línea.",
    "tituloJuegoDefault": "Juego",
    "escucharTextoAria": "Escuchar mi texto",
    "borrarTextoAria": "Borrar el texto",
    "areaLibreAria": "Escribe aquí lo que quieras",
    "areaLibrePlaceholder": "Escribe aquí...",
    "noHasEscrito": "Todavía no has escrito nada.",
    "muyBien": "¡Muy bien!",
    "muyBienNombre": "¡Muy bien, {nombre}!",
    "escribeTuNombre": "Escribe tu nombre.",
    "escribeLaPalabra": "Escribe la palabra.",
    "tituloTodasLasTeclas": "Todas las teclas",
    "instruccionTodasLasTeclas": "Pulsa todas las teclas de tu teclado. Cada tecla se enciende en la pantalla.",
    "retoSiguiente": "Pulsa la tecla {tecla} con el dedo {dedo} de la mano {mano}.",
    "retoSiguientePulgar": "Pulsa la tecla {tecla} con el pulgar.",
    "deTexto": "{hechas} de {total}",
    "escribeAria": "Escribe: {seq}",
    "pulsaTeclaAria": "Pulsa: {tecla}",
    "pulgarTexto": "Pulgar. La tecla de espacio.",
    "manoDedoTexto": "Mano {mano}. Dedo {dedo}.",
    "mayusTexto": "También mantén pulsada Mayús con el meñique de la mano {mano}.",
    "buscaTecla": "Busca la tecla en tu teclado.",
    "leccionTitulo": "Lección: {titulo}",
    "izquierdaEtiqueta": "Izquierda",
    "derechaEtiqueta": "Derecha",
    "dedo": {"lp":{"mano":"izquierda","nombre":"meñique"},"lr":{"mano":"izquierda","nombre":"anular"},"lm":{"mano":"izquierda","nombre":"medio"},"li":{"mano":"izquierda","nombre":"índice"},"ri":{"mano":"derecha","nombre":"índice"},"rm":{"mano":"derecha","nombre":"medio"},"rr":{"mano":"derecha","nombre":"anular"},"rp":{"mano":"derecha","nombre":"meñique"},"th":{"mano":"las dos","nombre":"pulgar"}},
    "teclaLabel": {"espacio":"espacio","tab":"Tab","mayus":"Mayús","intro":"Intro","borrar":"Borrar","inicio":"Inicio","fin":"Fin","pagArriba":"Re Pág","pagAbajo":"Av Pág","suprimir":"Supr"},
    "transferencia": "Esto te ayuda a escribir mensajes reales a la familia en el ordenador.",
    "etiquetaIdioma": "🌐 Idioma",
    "etiquetaIdiomaAria": "Elegir idioma",
    "etiquetaModoFoco": "🧘 Sin distracciones",
    "etiquetaModoFocoAria": "Activar o desactivar el modo sin distracciones",
    "etiquetaModoFocoOn": "✅ Sin distracciones: activado",
    "etiquetaModoFocoOff": "⬜ Sin distracciones: desactivado",
    "etiquetaTextoA": "A−",
    "etiquetaTextoAria": "Tamaño del texto",
    "etiquetaTextoAAria": "Aumentar o reducir el tamaño del texto",
    "etiquetaTema": "🌗 Tema",
    "etiquetaTemaAria": "Cambiar el tema claro, oscuro o alto contraste",
    "etiquetaTemaAuto": "Tema: automático",
    "etiquetaTemaClaro": "Tema: claro",
    "etiquetaTemaOscuro": "Tema: oscuro",
    "etiquetaTemaContraste": "Tema: alto contraste",
    
    /* Métricas: el producto no ha cerrado los detalles pero el botón
       se queda visible (y apagado por defecto) para que la persona
       usuaria lo encuentre y entienda que existe. La implementación
       actual muestra precisión (%) y PPM en vivo. */
    "etiquetaMetricas": "📊 Métricas",
    "etiquetaMetricasAria": "Activar o desactivar las métricas de precisión y velocidad",
    "etiquetaMetricasOn": "✅ Métricas: encendidas",
    "etiquetaMetricasOff": "⬜ Métricas: apagadas",

    /* Sonido espacial: el tono de acierto suena por el lado (izquierda
       o derecha) de la tecla pulsada, para reforzar la posición de la
       mano sin depender de la vista. */
    "etiquetaSonidoEspacial": "🎧 Sonido espacial",
    "etiquetaSonidoEspacialAria": "Activar o desactivar el sonido espacial",
    "etiquetaSonidoEspacialOn": "✅ Sonido espacial: encendido",
    "etiquetaSonidoEspacialOff": "⬜ Sonido espacial: apagado",

    "racha": "Racha: {n}",
    "rachaNueva": "¡Racha de {n}!",
    "rachaMejor": "Mejor racha: {n}",
    "insigniasTitulo": "Insignias",
    "insigniasVacia": "Aún no hay insignias. ¡Sigue practicando!",
    "insigniaPrimera": "🌟 Primera lección",
    "insigniaPosicion": "🖐️ Colocaste los dedos",
    "insigniaPalabras": "✏️ Tus primeras palabras",
    "insigniaNumeros": "🔢 Dominas los números",
    "insigniaTodas": "🌈 Todas las teclas",
    "insigniaLibre": "✍️ Escritura libre",
    "insigniaRacha5": "🔥 Racha de 5",
    "insigniaRacha10": "🔥 Racha de 10",
    "insigniaPrecision": "🎯 90 % de precisión",
    "nuevaInsignia": "¡Nueva insignia!",
    "precision": "Precisión: {n}%",
    "precisionCorto": "Prec. {n}%",
    "ppm": "PPM: {n}",
    "ppmCorto": "{n} PPM",
    "teclasPpm": "Teclas: {n}",
    "tiempoCorto": "{n}s",
    
    "abrirAjustesAria": "Abrir ajustes",
    "cerrarAjustesAria": "Cerrar ajustes",
    "headerAjustes": "Ajustes",
    "panelAjustes": "Ajustes de accesibilidad y juego",
    "ajustesAyuda": "Estos ajustes se guardan en este dispositivo.",
    "soloOrdenador": "Solo en el ordenador",
    "soloOrdenadorMotivo": "Teclatlon se usa con el teclado físico del ordenador. En un móvil o tablet el teclado que ves en pantalla es solo un dibujo: no se puede pulsar para escribir. Abre esta página desde un portátil o un PC.",
    "soloOrdenadorSugerencia": "Si tu móvil u ordenador tienen teclado físico, conecta uno por Bluetooth o USB y vuelve a intentarlo."
  }, 'es');
})();
