/* ============================================================
   Teclatlon — Texts (EN)
   Language-specific file. Loaded conditionally from index.html
   depending on App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "⌨️ Teclatlon",
    "nameScreenText": "Hi! What is your name? Type your name on the keyboard.",
    "listenNameExtra": " When you are done, tap the Done button.",
    "nameInputAria": "Type your name",
    "btnSaveName": "✅ Done",
    "btnSkipName": "Not now",
    "keyboardViewAria": "Keyboard view",
    "btnSimple": "🔤 Letters only",
    "btnNormal": "⌨️ Letters and numbers",
    "btnExtended": "🔢 With numbers on the side",
    "btnSimpleDetail": "You only see the letters. It is the simplest view.",
    "btnNormalDetail": "You see the letters and the numbers, like a normal keyboard.",
    "btnExtendedDetail": "You see the whole keyboard and, on the right, the number pad.",
    "btnColorsHands": "🎨 Colors: hands",
    "btnColorsFingers": "🎨 Colors: fingers",
    "legendFingers": "Each finger has its own color.",
    "legendHands": "Blue: left hand. Green: right hand.",
    "btnClearProgress": "🗑️ Erase my progress",
    "confirmClear": "Are you sure? Tap again to erase.",
    "clearedNotice": "Everything erased. You start again.",
    "greetingHello": "Hi!",
    "greetingWithName": "Hi, {name}!",
    "chooseGame": "Choose a game.",
    "modePlacementName": "Place your fingers",
    "modePlacementDetail": "Each finger has its key.",
    "modeLessonsName": "Step by step",
    "modeLessonsDetail": "Learn the letters in order.",
    "modeWordsName": "Words",
    "modeWordsDetail": "Type words and your name.",
    "modeAllKeysName": "All the keys",
    "modeAllKeysDetail": "Light up every key.",
    "modeNumbersName": "Numbers",
    "modeNumbersDetail": "Use the number pad.",
    "modeFreeName": "Free writing",
    "modeFreeDetail": "Type and listen to your text.",
    "modeTemplatesName": "Real texts",
    "modeTemplatesDetail": "Practice with an email or a letter.",
    "btnMyName": "✏️ My name",
    "btnMenu": "← Menu",
    "lessonsInstruction": "Finish a lesson to unlock the next one.",
    "lessonLockedAria": "Lesson {n} locked. Finish the previous one.",
    "templatesInstruction": "Choose a text to practice.",
    "templateInstruction": "Type the next line.",
    "gameTitleDefault": "Game",
    "listenTextAria": "Listen to my text",
    "clearTextAria": "Erase the text",
    "freeAreaAria": "Type anything you like here",
    "freeAreaPlaceholder": "Type here...",
    "nothingWrittenYet": "You have not written anything yet.",
    "wellDone": "Well done!",
    "wellDoneWithName": "Well done, {name}!",
    "typeYourName": "Type your name.",
    "typeTheWord": "Type the word.",
    "allKeysTitle": "All the keys",
    "allKeysInstruction": "Press every key on your keyboard. Each key lights up on the screen.",
    "challengeNextKey": "Press the {key} key with the {finger} finger of your {hand} hand.",
    "challengeNextKeyThumb": "Press the {key} key with your thumb.",
    "doneOfTotal": "{done} of {total}",
    "typeAria": "Type: {seq}",
    "pressKeyAria": "Press: {key}",
    "thumbText": "Thumb. The space bar.",
    "handFingerText": "{hand} hand. {finger} finger.",
    "shiftText": "Also hold Shift down with your {hand} little finger.",
    "findKey": "Find the key on your keyboard.",
    "lessonTitle": "Lesson: {title}",
    "lessonReview": "Review: press every key you have learned so far, in keyboard order.",
    "leftLabel": "Left",
    "rightLabel": "Right",
    "finger": {"lp":{"hand":"left","name":"little"},"lr":{"hand":"left","name":"ring"},"lm":{"hand":"left","name":"middle"},"li":{"hand":"left","name":"index"},"ri":{"hand":"right","name":"index"},"rm":{"hand":"right","name":"middle"},"rr":{"hand":"right","name":"ring"},"rp":{"hand":"right","name":"little"},"th":{"hand":"both","name":"thumb"}},
    "keyLabel": {"space":"space","tab":"Tab","shift":"Shift","enter":"Enter","backspace":"Backspace","home":"Home","end":"End","pageUp":"Page Up","pageDown":"Page Down","delete":"Delete"},
    "transferMessage": "This helps you write real messages to family on the computer.",
    "languageLabel": "🌐 Language",
    "languageLabelAria": "Choose language",
    "focusModeLabel": "🧘 Distraction-free",
    "focusModeLabelAria": "Turn distraction-free mode on or off",
    "focusModeLabelOn": "✅ Distraction-free: on",
    "focusModeLabelOff": "⬜ Distraction-free: off",
    "textSizeA": "A−",
    "textSizeAria": "Text size",
    "textSizeAdjustAria": "Increase or decrease the text size",
    "themeLabel": "🌗 Theme",
    "themeLabelAria": "Switch between light, dark or high contrast theme",
    "themeLabelAuto": "Theme: auto",
    "themeLabelLight": "Theme: light",
    "themeLabelDark": "Theme: dark",
    "themeLabelContrast": "Theme: high contrast",

    /* Metrics: the product has not finalised the details, but the
       toggle stays visible (off by default) so the user can find it.
       The current implementation shows live accuracy (%) and keys
       per minute. */
    "metricsLabel": "📊 Metrics",
    "metricsLabelAria": "Turn accuracy and speed metrics on or off",
    "metricsLabelOn": "✅ Metrics: on",
    "metricsLabelOff": "⬜ Metrics: off",

    /* Spatial sound: the success tone plays from the side (left or
       right) of the key that was pressed, reinforcing hand position
       without relying on sight. */
    "spatialSoundLabel": "🎧 Spatial sound",
    "spatialSoundLabelAria": "Turn spatial sound on or off",
    "spatialSoundLabelOn": "✅ Spatial sound: on",
    "spatialSoundLabelOff": "⬜ Spatial sound: off",

    "accuracy": "Accuracy: {n}%",
    "accuracyShort": "Acc. {n}%",
    "keysPerMinute": "PPM: {n}",
    "keysPerMinuteShort": "{n} PPM",
    "keysLabel": "Keys: {n}",
    "timeShort": "{n}s",

    "openSettingsAria": "Open settings",
    "closeSettingsAria": "Close settings",
    "settingsHeader": "Settings",
    "settingsPanel": "Accessibility and game settings",
    "settingsHelp": "These settings are saved on this device.",
    "computerOnly": "Computer only",
    "computerOnlyWhy": "Teclatlon is for practising typing on a computer keyboard.",
    "computerOnlyReason": "We need the physical keyboard to type. The keyboard drawn on screen cannot be tapped. On a phone or tablet there are no real keys to practise with.",
    "computerOnlySuggestion": "Open this page on a laptop or a PC. If your phone has a physical keyboard, pair it over Bluetooth or USB."
  }, 'en');
})();
