/* ============================================================
   Teclatlon — Texts (EN)
   Language-specific file. Loaded conditionally from index.html
   depending on App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "⌨️ Teclatlon",
    "nameScreenText": "Hi! What is your name? Type your name on the keyboard.",
    "listenNameExtra": " When you are done, tap the Done button.",
    "nameInputAria": "Type your name",
    "btnSaveName": "✅ Done",
    "btnSkipName": "Not now",
    "keyboardViewAria": "Keyboard view",
    "btnSimple": "🔤 Letters only",
    "btnNormal": "⌨️ Letters and numbers",
    "btnExtended": "🔢 With numbers on the side",
    "btnSimpleDetail": "You only see the letters. It is the simplest view.",
    "btnNormalDetail": "You see the letters and the numbers, like a normal keyboard.",
    "btnExtendedDetail": "You see the whole keyboard and, on the right, the number pad.",
    "btnColorsHands": "🎨 Colors: hands",
    "btnColorsFingers": "🎨 Colors: fingers",
    "legendFingers": "Each finger has its own color.",
    "legendHands": "Blue: left hand. Green: right hand.",
    "btnClearProgress": "🗑️ Erase my progress",
    "confirmClear": "Are you sure? Tap again to erase.",
    "clearedNotice": "Everything erased. You start again.",
    "greetingHello": "Hi!",
    "greetingWithName": "Hi, {name}!",
    "chooseGame": "Choose a game.",
    "modePlacementName": "Place your fingers",
    "modePlacementDetail": "Each finger has its key.",
    "modeLessonsName": "Step by step",
    "modeLessonsDetail": "Learn the letters in order.",
    "modeWordsName": "Words",
    "modeWordsDetail": "Type words and your name.",
    "modeAllKeysName": "All the keys",
    "modeAllKeysDetail": "Light up every key.",
    "modeNumbersName": "Numbers",
    "modeNumbersDetail": "Use the number pad.",
    "modeFreeName": "Free writing",
    "modeFreeDetail": "Type and listen to your text.",
    "modeTemplatesName": "Real texts",
    "modeTemplatesDetail": "Practice with an email or a letter.",
    "btnMyName": "✏️ My name",
    "btnMenu": "← Menu",
    "lessonsInstruction": "Finish a lesson to unlock the next one.",
    "lessonLockedAria": "Lesson {n} locked. Finish the previous one.",
    "templatesInstruction": "Choose a text to practice.",
    "templateInstruction": "Type the next line.",
    "gameTitleDefault": "Game",
    "listenTextAria": "Listen to my text",
    "clearTextAria": "Erase the text",
    "freeAreaAria": "Type anything you like here",
    "freeAreaPlaceholder": "Type here...",
    "nothingWrittenYet": "You have not written anything yet.",
    "wellDone": "Well done!",
    "wellDoneWithName": "Well done, {name}!",
    "typeYourName": "Type your name.",
    "typeTheWord": "Type the word.",
    "allKeysTitle": "All the keys",
    "allKeysInstruction": "Press every key on your keyboard. Each key lights up on the screen.",
    "challengeNextKey": "Press the {key} key with the {finger} finger of your {hand} hand.",
    "challengeNextKeyThumb": "Press the {key} key with your thumb.",
    "doneOfTotal": "{done} of {total}",
    "typeAria": "Type: {seq}",
    "pressKeyAria": "Press: {key}",
    "thumbText": "Thumb. The space bar.",
    "handFingerText": "{hand} hand. {finger} finger.",
    "shiftText": "Also hold Shift down with your {hand} little finger.",
    "findKey": "Find the key on your keyboard.",
    "lessonTitle": "Lesson: {title}",
    "lessonReview": "Review: press every key you have learned so far, in keyboard order.",
    "leftLabel": "Left",
    "rightLabel": "Right",
    "finger": {"lp":{"hand":"left","name":"little"},"lr":{"hand":"left","name":"ring"},"lm":{"hand":"left","name":"middle"},"li":{"hand":"left","name":"index"},"ri":{"hand":"right","name":"index"},"rm":{"hand":"right","name":"middle"},"rr":{"hand":"right","name":"ring"},"rp":{"hand":"right","name":"little"},"th":{"hand":"both","name":"thumb"}},
    "keyLabel": {"space":"space","tab":"Tab","shift":"Shift","enter":"Enter","backspace":"Backspace","home":"Home","end":"End","pageUp":"Page Up","pageDown":"Page Down","delete":"Delete"},
    "transferMessage": "This helps you write real messages to family on the computer.",
    "languageLabel": "🌐 Language",
    "languageLabelAria": "Choose language",
    "focusModeLabel": "🧘 Distraction-free",
    "focusModeLabelAria": "Turn distraction-free mode on or off",
    "focusModeLabelOn": "✅ Distraction-free: on",
    "focusModeLabelOff": "⬜ Distraction-free: off",
    "textSizeA": "A−",
    "textSizeAria": "Text size",
    "textSizeAdjustAria": "Increase or decrease the text size",
    "themeLabel": "🌗 Theme",
    "themeLabelAria": "Switch between light, dark or high contrast theme",
    "themeLabelAuto": "Theme: auto",
    "themeLabelLight": "Theme: light",
    "themeLabelDark": "Theme: dark",
    "themeLabelContrast": "Theme: high contrast",

    /* Metrics: the product has not finalised the details, but the
       toggle stays visible (off by default) so the user can find it.
       The current implementation shows live accuracy (%) and keys
       per minute. */
    "metricsLabel": "📊 Metrics",
    "metricsLabelAria": "Turn accuracy and speed metrics on or off",
    "metricsLabelOn": "✅ Metrics: on",
    "metricsLabelOff": "⬜ Metrics: off",

    /* Spatial sound: the success tone plays from the side (left or
       right) of the key that was pressed, reinforcing hand position
       without relying on sight. */
    "spatialSoundLabel": "🎧 Spatial sound",
    "spatialSoundLabelAria": "Turn spatial sound on or off",
    "spatialSoundLabelOn": "✅ Spatial sound: on",
    "spatialSoundLabelOff": "⬜ Spatial sound: off",

    "accuracy": "Accuracy: {n}%",
    "accuracyShort": "Acc. {n}%",
    "keysPerMinute": "PPM: {n}",
    "keysPerMinuteShort": "{n} PPM",
    "keysLabel": "Keys: {n}",
    "timeShort": "{n}s",

    "openSettingsAria": "Open settings",
    "closeSettingsAria": "Close settings",
    "settingsHeader": "Settings",
    "settingsPanel": "Accessibility and game settings",
    "settingsHelp": "These settings are saved on this device.",
    "computerOnly": "Computer only",
    "computerOnlyWhy": "Teclatlon is for practising typing on a computer keyboard.",
    "computerOnlyReason": "We need the physical keyboard to type. The keyboard drawn on screen cannot be tapped. On a phone or tablet there are no real keys to practise with.",
    "computerOnlySuggestion": "Open this page on a laptop or a PC. If your phone has a physical keyboard, pair it over Bluetooth or USB.",

    /* --- /legal (Data protection) ---------------------------------------
       English mirror of the legal block above. Same prefix, same keys,
       same comments. The check.js parity rule verifies every key in the
       'es' dict also exists in 'en' and vice versa. */
    legal: {
      pageTitle: 'Data protection',
      tagline: 'No registration. No cookies. No analytics.',
      lead: 'Teclatlon does not ask for your personal data. Everything it saves lives only on this device. Here we explain, in detail, what we save and why.',
      navResponsible: 'Who processes your data',
      navData: 'What we save',
      navRights: 'Your rights',
      navMinors: 'All ages',
      navContact: 'Changes and contact',
      responsibleTitle: 'Who processes your data',
      responsibleP1a: 'Teclatlon is an initiative of ',
      responsibleP1b: ', an independent studio that develops and maintains the application. There is no server of our own that receives or stores your data: the application is a set of static pages that run in your browser.',
      responsibleP2a: 'The full source code is public and auditable in the ',
      responsibleP2Link: 'GitHub repository',
      responsibleP2b: '. Any question about this page can be raised by opening an issue there.',
      dataTitle: 'What we save and why',
      dataP1: 'Teclatlon works without accounts, cookies or analytics: we don’t know who you are or how you use the application.',
      dataP2: 'The only thing that gets saved lives in your browser’s localStorage, on your own device, and is never sent to any server:',
      dataItem1Label: 'Game progress',
      dataItem1Text: 'the stars earned, the lessons completed, the badges earned, and your best streak of correct keystrokes.',
      dataItem2Label: 'Chosen language',
      dataItem2Text: 'so you don’t have to choose it again every time you open the app.',
      dataItem3Label: 'Accessibility and gameplay settings',
      dataItem3Text: 'text size, theme, focus mode, easy read, and other panel settings.',
      dataP3: 'We never save: name, passwords, free text typed in, unique personal identifiers, failures, time taken, number of attempts, comparisons with other people, or detailed usage histories.',
      dataP4: 'This information is kept until it is deleted, and its only purpose is to stop your progress being lost when you close the application.',
      rightsTitle: 'Your rights and how to exercise them',
      rightsP1: 'Since everything saved lives on your device and not on a server, you have direct control: you can view it, change it or delete it at any time, without asking us.',
      rightsP2: 'To delete it, use the "Erase my progress" button in the app itself, or clear your browser’s site data for this website from its settings.',
      rightsLinkApp: 'Go to Teclatlon',
      minorsTitle: 'All ages and abilities',
      minorsP1: 'Teclatlon is designed to be used autonomously by anyone, regardless of age or abilities, including those who are just starting to use a physical keyboard.',
      minorsP2: 'Because the application does not collect personal data on any server, no guardian consent is needed to process data: there is no processing to authorise. We do recommend the usual supervision a family or professional gives to how any device is used.',
      contactTitle: 'Changes and contact',
      contactP1: 'This page may be updated if the application changes. The change history is public in the GitHub repository.',
      contactP2: 'Last updated: 30 August 2026.',
      contactP3a: 'For questions about this page, open an issue in the ',
      contactP3Link: 'GitHub repository',
      contactP3b: '.',
      footerActivities: 'Go to the app'
    },

    /* --- /about (Project presentation) --------------------------------- */
    about: {
      pageTitle: 'Project presentation',
      routeNotice: 'This page is not linked from the app. The only way here is typing the address.',
      tagline: 'An app for autonomy.',
      lead1: 'Teclatlon is a ',
      leadStrong: 'touch-typing web app with a physical keyboard',
      lead2: ' built so anyone, with or without prior experience, can learn to type with all ten fingers, without pressure and with respect for their privacy.',
      navOrigin: 'The origin',
      navPrinciples: 'The principles',
      navTech: 'How it is built',
      navAreas: 'The areas of work',
      navSiblings: 'Sibling projects',
      navAuthorship: 'Who makes it',
      navCollaborate: 'How to help',
      originTitle: 'The origin',
      originP1a: 'Teclatlon comes from a question that comes up at the end of every learning support session: ',
      originP1em: 'what happens between one session and the next?',
      originP2: 'The person using the app practices with whoever supports them in a clinic or at home, but afterwards they are on their own at home, at school, or in their free time. We wanted a tool that respected that autonomy, gave families peace of mind, and served whoever supports them as a complement between sessions, not a replacement.',
      originP3: 'This app is the result: a single typing tool, with several keyboard modes and per-finger colour coding, in Plain Language and accessible, designed so the person using it can practice at their own pace.',
      principlesTitle: 'The principles we won’t compromise on',
      principlesIntro: 'These ideas are written into the code first and the text second. If a decision breaks them, that decision is wrong.',
      principleAutonomyTitle: '🤲 Real autonomy',
      principleAutonomyText: 'The person using the app can use it without a professional beside them. If it needs constant help, something has not been solved well.',
      principleNoPressureTitle: '🚫 No pressure',
      principleNoPressureText: 'No timers, no "game over", no negative scores. Mistakes get encouragement, and retrying is unlimited.',
      principlePrivacyTitle: '🔒 Privacy by default',
      principlePrivacyText: 'No sign-up, no cookies, no analytics, no accounts. All progress is saved only on the person’s own device.',
      principleEasyReadTitle: '📖 Plain Language',
      principleEasyReadText: 'Short sentences, one idea per sentence, everyday vocabulary. Zero jargon in the interface the person using the app sees.',
      principleAccessibilityTitle: '♿ Accessibility for everyone',
      principleAccessibilityText: 'A large on-screen keyboard with per-finger coloured keys, high contrast, audio only when gamification or the activity design requires it (e.g. hearing the letter to type), full keyboard navigation, and respect for the system’s reduced-motion setting.',
      principleSoberTechTitle: '🧱 Sober technology',
      principleSoberTechText: 'HTML, CSS and JavaScript, no frameworks. Works offline and can be installed as an app. Open source, in a public repository.',
      techTitle: 'How it is built',
      techIntro1: 'Teclatlon is an installable web app (PWA) made up of more than ',
      techIntroStrong: '5 static HTML pages',
      techIntro2: ': the landing page, the on-screen keyboard, and hidden routes for families, professionals and maintenance.',
      techItem1Label: 'No server of its own',
      techItem1Text: 'it is a set of files served by static hosting. No backend, no databases, no API of its own.',
      techItem2Label: 'Works offline',
      techItem2Text: 'once installed, it opens even without an internet connection thanks to the service worker and local cache.',
      techItem3Label: 'Persistence only in',
      techItem3Text: 'progress (stars, practised letters, chosen keyboard mode) lives in the device’s browser. It is never sent anywhere.',
      techItem4Label: 'No frameworks, no build step',
      techItem4Text1: 'classic JavaScript compatible with older browsers and with the',
      techItem4Text2: ' protocol. Built so a junior developer can read and modify a lesson without surprises.',
      techItem5Label: 'Open source (MIT license)',
      techItem5Text: 'anyone can read it, audit it and suggest improvements. Product decisions are written down in this repository, not in closed-door presentations.',
      techItem6Label: 'Internationalized from day one',
      techItem6Text: 'every piece of text lives in a file per language. Today Teclatlon is available in Spanish (Spain) and English.',
      techItem7Label: 'External dependencies: none',
      techItem7Text: ', except for downloading the Atkinson Hyperlegible and Nunito typefaces (chosen for their high legibility).',
      areasTitle: 'The areas of work',
      areasIntro1: 'A single tool, but typing is organised into ',
      areasIntroStrong: 'six blocks by hand and finger',
      areasIntro2: ', each with its own colour on the on-screen keyboard. Each lesson trains one block, and the person advances at their own pace: they can start with the index fingers and work up to typing with all ten.',
      areaLeftHandTitle: '✋ Left hand',
      areaLeftHandText: 'The five keys typed with the left hand (and the thumbs for the space bar).',
      areaLeftHandCount: '5 keys',
      areaRightHandTitle: '🤚 Right hand',
      areaRightHandText: 'The five keys typed with the right hand.',
      areaRightHandCount: '5 keys',
      areaRingFingerTitle: '💍 Ring finger',
      areaRingFingerText: 'The keys pressed by the ring fingers (one on each hand).',
      areaRingFingerCount: '2 keys',
      areaMiddleFingerTitle: '🖕 Middle finger',
      areaMiddleFingerText: 'The keys pressed by the middle fingers (one on each hand).',
      areaMiddleFingerCount: '2 keys',
      areaPinkyTitle: '🤞 Little finger',
      areaPinkyText: 'The keys pressed by the little fingers (one on each hand).',
      areaPinkyCount: '2 keys',
      areaModesTitle: '🎹 Keyboard modes',
      areaModesText: 'Simple, normal, extended keyboard and per-finger colour coding.',
      areaModesCount: '4 modes',
      areasNote1: 'Total: ',
      areasNoteStrong: '1 tool, several lessons',
      areasNote2: ', organized so the person chooses by interest, not by obligation. The menu order is not an itinerary: everyone takes their own path.',
      siblingsTitle: 'Sibling projects',
      siblingsIntro: 'Teclatlon is one of a small group of sibling projects: same team, same accessibility-first philosophy, and no server of their own. Each one is an independent service, with its own domain, reachable from here.',
      siblingRoutimeName: 'Routime',
      siblingRoutimeText: 'Daily routines and autonomy.',
      siblingCalculiaName: 'Calculia',
      siblingCalculiaText: 'Math and logical reasoning.',
      siblingMemofunName: 'Memofun',
      siblingMemofunText: 'Memory and attention.',
      siblingOkeymoneyName: 'Okeymoney',
      siblingOkeymoneyText: 'Personal finance and everyday autonomy.',
      siblingSinonimiaName: 'Sinonimia',
      siblingSinonimiaText: 'Plain-language dictionary.',
      siblingLinkHint: 'Opens in a new tab.',
      authorshipTitle: 'Who makes it',
      authorshipP1a: 'Teclatlon is an initiative by ',
      authorshipP1b: ', an independent studio working on open projects with social and educational impact.',
      authorshipP2: 'The app is built with the involvement of people with diverse learning profiles, families, support professionals and teachers, who test every change and review the content before it reaches production.',
      authorshipP3: 'The code, the text and the decisions are published openly so anyone or any team can audit them, learn from them, and adapt them to other contexts.',
      collaborateTitle: 'How to help',
      collaborateIntro: 'Teclatlon is an open project. There are ways to help that do not require coding:',
      collaborateItem1Label: 'Try it and share feedback',
      collaborateItem1Text: 'families, therapists and the people who use the app and report what works and what does not are the key piece of the project. Plain Language mistakes, unfriendly tone and lessons that are hard to follow only surface through actual use.',
      collaborateItem2Label: 'Suggest lessons',
      collaborateItem2Text: 'if a typing skill is not covered, or is covered in a way that could be improved, a new lesson can be proposed. A professional validates the didactic description before it becomes code.',
      collaborateItem3Label: 'Review content',
      collaborateItem3Text: 'translations, culturally appropriate examples, accessible explanations. The interface the person using the app sees is in Plain Language, and outside eyes help a lot.',
      collaborateItem4Label: 'Contribute code',
      collaborateItem4Text: 'the repository is public. Both small changes (an icon, a translation, a style fix) and large ones (new lessons, accessibility, support for more languages) are welcome as long as they respect the project’s principles.',
      collaborateItem5Label: 'Spread the word',
      collaborateItem5Text: 'tell people it exists. Many families, professionals and centers do not know tools like this exist until someone shows it to them.',
      collaborateOutro1: 'All the documentation needed to get started is in the',
      collaborateOutro3: 'and',
      collaborateOutro4: 'files of the repository.',
      footerActivities: 'Go to the app'
    }
  }, 'en');
})();
