/* ============================================================
   Teclatlon — Textos (ES)
   Archivo específico del idioma. Se carga condicionalmente desde
   index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "⌨️ Teclatlon",
    "textoNombre": "¡Hola! ¿Cómo te llamas? Escribe tu nombre con el teclado.",
    "escucharNombreExtra": " Cuando termines, toca el botón Listo.",
    "inputNombreAria": "Escribe tu nombre",
    "btnGuardarNombre": "✅ Listo",
    "btnSinNombre": "Ahora no",
    "tipoTecladoAria": "Tipo de teclado",
    "btnSimple": "🔤 Simple",
    "btnNormal": "⌨️ Normal",
    "btnExtendido": "🔢 Extendido",
    "btnColoresManos": "🎨 Colores: manos",
    "btnColoresDedos": "🎨 Colores: dedos",
    "leyendaDedos": "Cada dedo tiene un color.",
    "leyendaManos": "Azul: mano izquierda. Verde: mano derecha.",
    "btnBorrarProgreso": "🗑️ Borrar mi progreso",
    "confirmarBorrado": "¿Seguro? Toca otra vez para borrar.",
    "avisoBorrado": "Todo borrado. Empiezas de nuevo.",
    "saludoHola": "¡Hola!",
    "saludoConNombre": "¡Hola, {nombre}!",
    "eligeJuego": "Elige un juego.",
    "modoPosicionNombre": "Coloca los dedos",
    "modoPosicionDetalle": "Cada dedo tiene su tecla.",
    "modoLeccionesNombre": "Paso a paso",
    "modoLeccionesDetalle": "Aprende las letras en orden.",
    "modoPalabrasNombre": "Palabras",
    "modoPalabrasDetalle": "Escribe palabras y tu nombre.",
    "modoTodasNombre": "Todas las teclas",
    "modoTodasDetalle": "Enciende todas las teclas.",
    "modoNumerosNombre": "Números",
    "modoNumerosDetalle": "Usa el teclado de números.",
    "modoLibreNombre": "Escribe libre",
    "modoLibreDetalle": "Escribe y escucha tu texto.",
    "btnMiNombre": "✏️ Mi nombre",
    "btnMenu": "← Menú",
    "leccionesInstruccion": "Termina una lección para abrir la siguiente.",
    "leccionCerradaAria": "Lección {n} cerrada. Termina la anterior.",
    "tituloJuegoDefault": "Juego",
    "escucharTextoAria": "Escuchar mi texto",
    "borrarTextoAria": "Borrar el texto",
    "areaLibreAria": "Escribe aquí lo que quieras",
    "areaLibrePlaceholder": "Escribe aquí...",
    "noHasEscrito": "Todavía no has escrito nada.",
    "muyBien": "¡Muy bien!",
    "muyBienNombre": "¡Muy bien, {nombre}!",
    "escribeTuNombre": "Escribe tu nombre.",
    "escribeLaPalabra": "Escribe la palabra.",
    "tituloTodasLasTeclas": "Todas las teclas",
    "instruccionTodasLasTeclas": "Pulsa todas las teclas de tu teclado. Cada tecla se enciende en la pantalla.",
    "deTexto": "{hechas} de {total}",
    "escribeAria": "Escribe: {seq}",
    "pulgarTexto": "Pulgar. La tecla de espacio.",
    "manoDedoTexto": "Mano {mano}. Dedo {dedo}.",
    "buscaTecla": "Busca la tecla en tu teclado.",
    "leccionTitulo": "Lección: {titulo}",
    "izquierdaEtiqueta": "Izquierda",
    "derechaEtiqueta": "Derecha",
    "dedo": {"lp":{"mano":"izquierda","nombre":"meñique"},"lr":{"mano":"izquierda","nombre":"anular"},"lm":{"mano":"izquierda","nombre":"medio"},"li":{"mano":"izquierda","nombre":"índice"},"ri":{"mano":"derecha","nombre":"índice"},"rm":{"mano":"derecha","nombre":"medio"},"rr":{"mano":"derecha","nombre":"anular"},"rp":{"mano":"derecha","nombre":"meñique"},"th":{"mano":"las dos","nombre":"pulgar"}},
    "teclaLabel": {"espacio":"espacio","tab":"Tab","mayus":"Mayús","intro":"Intro","borrar":"Borrar"},
    "transferencia": "Esto te ayuda a escribir mensajes reales a la familia en el ordenador."
  }, 'es');
})();
