/* ===================================================================
   Teclatlon — About page text (EN). Auto-extracted from the
   =================================================================== */
(function () {
  'use strict';

  App.i18n.register({
    "areaLeftHandCount": "5 keys",
    "areaLeftHandText": "The five keys typed with the left hand (and the thumbs for the space bar).",
    "areaLeftHandTitle": "✋ Left hand",
    "areaMiddleFingerCount": "2 keys",
    "areaMiddleFingerText": "The keys pressed by the middle fingers (one on each hand).",
    "areaMiddleFingerTitle": "🖕 Middle finger",
    "areaModesCount": "4 modes",
    "areaModesText": "Simple, normal, extended keyboard and per-finger colour coding.",
    "areaModesTitle": "🎹 Keyboard modes",
    "areaPinkyCount": "2 keys",
    "areaPinkyText": "The keys pressed by the little fingers (one on each hand).",
    "areaPinkyTitle": "🤞 Little finger",
    "areaRightHandCount": "5 keys",
    "areaRightHandText": "The five keys typed with the right hand.",
    "areaRightHandTitle": "🤚 Right hand",
    "areaRingFingerCount": "2 keys",
    "areaRingFingerText": "The keys pressed by the ring fingers (one on each hand).",
    "areaRingFingerTitle": "💍 Ring finger",
    "areasIntro1": "A single tool, but typing is organised into ",
    "areasIntro2": ", each with its own colour on the on-screen keyboard. Each lesson trains one block, and the person advances at their own pace: they can start with the index fingers and work up to typing with all ten.",
    "areasIntroStrong": "six blocks by hand and finger",
    "areasNote1": "Total: ",
    "areasNote2": ", organized so the person chooses by interest, not by obligation. The menu order is not an itinerary: everyone takes their own path.",
    "areasNoteStrong": "1 tool, several lessons",
    "areasTitle": "The areas of work",
    "authorshipP1a": "Teclatlon is an initiative by ",
    "authorshipP1b": ", an independent studio working on open projects with social and educational impact.",
    "authorshipP2": "The app is built with the involvement of people with diverse learning profiles, families, support professionals and teachers, who test every change and review the content before it reaches production.",
    "authorshipP3": "The code, the text and the decisions are published openly so anyone or any team can audit them, learn from them, and adapt them to other contexts.",
    "authorshipTitle": "Who makes it",
    "collaborateIntro": "Teclatlon is an open project. There are ways to help that do not require coding:",
    "collaborateItem1Label": "Try it and share feedback",
    "collaborateItem1Text": "families, therapists and the people who use the app and report what works and what does not are the key piece of the project. Plain Language mistakes, unfriendly tone and lessons that are hard to follow only surface through actual use.",
    "collaborateItem2Label": "Suggest lessons",
    "collaborateItem2Text": "if a typing skill is not covered, or is covered in a way that could be improved, a new lesson can be proposed. A professional validates the didactic description before it becomes code.",
    "collaborateItem3Label": "Review content",
    "collaborateItem3Text": "translations, culturally appropriate examples, accessible explanations. The interface the person using the app sees is in Plain Language, and outside eyes help a lot.",
    "collaborateItem4Label": "Contribute code",
    "collaborateItem4Text": "the repository is public. Both small changes (an icon, a translation, a style fix) and large ones (new lessons, accessibility, support for more languages) are welcome as long as they respect the project’s principles.",
    "collaborateItem5Label": "Spread the word",
    "collaborateItem5Text": "tell people it exists. Many families, professionals and centers do not know tools like this exist until someone shows it to them.",
    "collaborateOutro1": "All the documentation needed to get started is in the",
    "collaborateOutro3": "and",
    "collaborateOutro4": "files of the repository.",
    "collaborateTitle": "How to help",
    "footerActivities": "Go to the app",
    "footerDataProtection": "Data protection",
    "footerTeamGuide": "Who builds it",
    "footerSettings": "Settings",
    "lead1": "Teclatlon is a ",
    "lead2": " built so anyone, with or without prior experience, can learn to type with all ten fingers, without pressure and with respect for their privacy.",
    "leadStrong": "touch-typing web app with a physical keyboard",
    "navAreas": "The areas of work",
    "navAuthorship": "Who makes it",
    "navCollaborate": "How to help",
    "navOrigin": "The origin",
    "navPrinciples": "The principles",
    "navSiblings": "Sibling projects",
    "navTech": "How it is built",
    "originP1a": "Teclatlon comes from a question that comes up at the end of every learning support session: ",
    "originP1em": "what happens between one session and the next?",
    "originP2": "The person using the app practices with whoever supports them in a clinic or at home, but afterwards they are on their own at home, at school, or in their free time. We wanted a tool that respected that autonomy, gave families peace of mind, and served whoever supports them as a complement between sessions, not a replacement.",
    "originP3": "This app is the result: a single typing tool, with several keyboard modes and per-finger colour coding, in Plain Language and accessible, designed so the person using it can practice at their own pace.",
    "originTitle": "The origin",
    "pageTitle": "Project presentation",
    "principleAccessibilityText": "A large on-screen keyboard with per-finger coloured keys, high contrast, audio only when gamification or the activity design requires it (e.g. hearing the letter to type), full keyboard navigation, and respect for the system’s reduced-motion setting.",
    "principleAccessibilityTitle": "♿ Accessibility for everyone",
    "principleAutonomyText": "The person using the app can use it without a professional beside them. If it needs constant help, something has not been solved well.",
    "principleAutonomyTitle": "🤲 Real autonomy",
    "principleEasyReadText": "Short sentences, one idea per sentence, everyday vocabulary. Zero jargon in the interface the person using the app sees.",
    "principleEasyReadTitle": "📖 Plain Language",
    "principleNoPressureText": "No timers, no \"game over\", no negative scores. Mistakes get encouragement, and retrying is unlimited.",
    "principleNoPressureTitle": "🚫 No pressure",
    "principlePrivacyText": "No sign-up, no cookies, no analytics, no accounts. All progress is saved only on the person’s own device.",
    "principlePrivacyTitle": "🔒 Privacy by default",
    "principleSoberTechText": "HTML, CSS and JavaScript, no frameworks. Works offline and can be installed as an app. Open source, in a public repository.",
    "principleSoberTechTitle": "🧱 Sober technology",
    "principlesIntro": "These ideas are written into the code first and the text second. If a decision breaks them, that decision is wrong.",
    "principlesTitle": "The principles we won’t compromise on",
    "routeNotice": "This page is not linked from the app. The only way here is typing the address.",
    "siblingCalculiaName": "Calculia",
    "siblingCalculiaText": "Math and logical reasoning.",
    "siblingLinkHint": "Opens in a new tab.",
    "siblingMemofunName": "Memofun",
    "siblingMemofunText": "Memory and attention.",
    "siblingOkeymoneyName": "Okeymoney",
    "siblingOkeymoneyText": "Personal finance and everyday autonomy.",
    "siblingRoutimeName": "Routime",
    "siblingRoutimeText": "Daily routines and autonomy.",
    "siblingSinonimiaName": "Sinonimia",
    "siblingSinonimiaText": "Plain-language dictionary.",
    "siblingsIntro": "Teclatlon is one of a small group of sibling projects: same team, same accessibility-first philosophy, and no server of their own. Each one is an independent service, with its own domain, reachable from here.",
    "siblingsTitle": "Sibling projects",
    "tagline": "An app for autonomy.",
    "techIntro1": "Teclatlon is an installable web app (PWA) made up of more than ",
    "techIntro2": ": the landing page, the on-screen keyboard, and hidden routes for families, professionals and maintenance.",
    "techIntroStrong": "5 static HTML pages",
    "techItem1Label": "No server of its own",
    "techItem1Text": "it is a set of files served by static hosting. No backend, no databases, no API of its own.",
    "techItem2Label": "Works offline",
    "techItem2Text": "once installed, it opens even without an internet connection thanks to the service worker and local cache.",
    "techItem3Label": "Persistence only in",
    "techItem3Text": "progress (stars, practised letters, chosen keyboard mode) lives in the device’s browser. It is never sent anywhere.",
    "techItem4Label": "No frameworks, no build step",
    "techItem4Text1": "classic JavaScript compatible with older browsers and with the",
    "techItem4Text2": " protocol. Built so a junior developer can read and modify a lesson without surprises.",
    "techItem5Label": "Open source (MIT license)",
    "techItem5Text": "anyone can read it, audit it and suggest improvements. Product decisions are written down in this repository, not in closed-door presentations.",
    "techItem6Label": "Internationalized from day one",
    "techItem6Text": "every piece of text lives in a file per language. Today Teclatlon is available in Spanish (Spain) and English.",
    "techItem7Label": "External dependencies: none",
    "techItem7Text": ", except for downloading the Atkinson Hyperlegible and Nunito typefaces (chosen for their high legibility).",
    "techTitle": "How it is built"
  }, "en");
})();
