/* ===================================================================
   Teclatlon — About page text (ES). Auto-extracted from the
   =================================================================== */
(function () {
  'use strict';

  App.i18n.register({
    "areaLeftHandCount": "5 teclas",
    "areaLeftHandText": "Las cinco teclas que se escriben con la mano izquierda (y los pulgares para el espacio).",
    "areaLeftHandTitle": "✋ Mano izquierda",
    "areaMiddleFingerCount": "2 teclas",
    "areaMiddleFingerText": "Las teclas que pulsan los dedos corazón (uno en cada mano).",
    "areaMiddleFingerTitle": "🖕 Dedo corazón",
    "areaModesCount": "4 modos",
    "areaModesText": "Teclado simple, normal, extendido y con colores por dedo.",
    "areaModesTitle": "🎹 Modos de teclado",
    "areaPinkyCount": "2 teclas",
    "areaPinkyText": "Las teclas que pulsan los meñiques (uno en cada mano).",
    "areaPinkyTitle": "🤞 Meñique",
    "areaRightHandCount": "5 teclas",
    "areaRightHandText": "Las cinco teclas que se escriben con la mano derecha.",
    "areaRightHandTitle": "🤚 Mano derecha",
    "areaRingFingerCount": "2 teclas",
    "areaRingFingerText": "Las teclas que pulsan los dedos anulares (uno en cada mano).",
    "areaRingFingerTitle": "💍 Dedo anular",
    "areasIntro1": "Una sola herramienta, pero la mecanografía se organiza en ",
    "areasIntro2": ", cada uno con su color identificativo en el teclado virtual. Cada lección trabaja un bloque, y la persona avanza a su ritmo: puede empezar por el índice y subir hasta escribir con los diez dedos.",
    "areasIntroStrong": "seis bloques por mano y dedo",
    "areasNote1": "Total: ",
    "areasNote2": ", organizadas para que la persona elija por interés, no por obligación. El orden del menú no es un itinerario: cada persona hace su propio camino.",
    "areasNoteStrong": "1 herramienta, varias lecciones",
    "areasTitle": "Las áreas de trabajo",
    "authorshipP1a": "Teclatlon es una iniciativa de ",
    "authorshipP1b": ", un estudio independiente que trabaja en proyectos abiertos con impacto social y educativo.",
    "authorshipP2": "La aplicación se construye con la participación de personas con perfiles de aprendizaje diversos, familias, profesionales de apoyo y profesorado, que prueban cada cambio y revisan el contenido antes de que llegue a producción.",
    "authorshipP3": "El código, el texto y las decisiones se publican en abierto para que cualquier persona o equipo pueda auditarlos, aprender de ellos y adaptarlos a otros contextos.",
    "authorshipTitle": "Quiénes la hacen",
    "collaborateIntro": "Teclatlon es un proyecto abierto. Hay formas de colaborar que no requieren programar:",
    "collaborateItem1Label": "Probar y compartir feedback",
    "collaborateItem1Text": "las familias, terapeutas y personas usuarias que prueban la aplicación y cuentan qué funciona y qué no, son la pieza clave del proyecto. Los errores de Lectura Fácil, los tonos poco amables y las lecciones que cuesta entender se detectan usándolas.",
    "collaborateItem2Label": "Proponer lecciones",
    "collaborateItem2Text": "si una habilidad de mecanografía no está cubierta o se trabaja de una forma mejorable, se puede proponer una lección nueva. La descripción didáctica la valida un profesional antes de pasar a código.",
    "collaborateItem3Label": "Revisar contenido",
    "collaborateItem3Text": "traducciones, ejemplos culturalmente adecuados, explicaciones accesibles. La interfaz que ve la persona usuaria es en Lectura Fácil y se beneficia especialmente de ojos ajenos.",
    "collaborateItem4Label": "Contribuir código",
    "collaborateItem4Text": "el repositorio es público. Cambios pequeños (un icono, una traducción, una corrección de estilo) y grandes (lecciones nuevas, accesibilidad, soporte para más idiomas) se aceptan siempre que respeten los principios del proyecto.",
    "collaborateItem5Label": "Difundir",
    "collaborateItem5Text": "contar que existe. Muchas familias, profesionales y centros no saben que hay herramientas como esta hasta que alguien se la enseña.",
    "collaborateOutro1": "Toda la documentación necesaria para empezar está en los archivos",
    "collaborateOutro3": "y",
    "collaborateOutro4": "del repositorio.",
    "collaborateTitle": "Cómo ayudar",
    "footerActivities": "Ir a la aplicación",
    "lead1": "Teclatlon es una ",
    "lead2": " pensada para que cualquier persona, con o sin experiencia previa, aprenda a escribir con los diez dedos, sin presión y con respeto a su privacidad.",
    "leadStrong": "aplicación web de mecanografía con teclado físico",
    "navAreas": "Las áreas de trabajo",
    "navAuthorship": "Quiénes la hacen",
    "navCollaborate": "Cómo ayudar",
    "navOrigin": "El origen",
    "navPrinciples": "Los principios",
    "navSiblings": "Proyectos hermanos",
    "navTech": "Cómo está hecha",
    "originP1a": "Teclatlon nace de una pregunta que se repite al final de cada sesión de apoyo al aprendizaje: ",
    "originP1em": "¿qué pasa entre una sesión y la siguiente?",
    "originP2": "La persona usuaria practica con quien le acompaña en consulta o en casa, pero después está sola en casa, en el colegio o en su tiempo libre. Queríamos una herramienta que respetase esa autonomía, que diese seguridad a las familias y que sirviese a quien acompaña como complemento entre sesiones, no como sustituto.",
    "originP3": "Esta aplicación es el resultado: una sola herramienta de mecanografía, con varios modos de teclado y por colores por dedo, en Lectura Fácil y accesible, pensada para que la persona usuaria pueda practicar a su propio ritmo.",
    "originTitle": "El origen",
    "pageTitle": "Presentación del proyecto",
    "principleAccessibilityText": "Teclado físico de gran tamaño con teclas de color por dedo, alto contraste, audio solo cuando la gamificación o el diseño de la actividad lo requiera (p. ej. escuchar la letra a escribir), navegación completa por teclado, y respeto al modo de pocas animaciones del sistema.",
    "principleAccessibilityTitle": "♿ Accesibilidad universal",
    "principleAutonomyText": "La persona usuaria puede usar la aplicación sin un profesional al lado. Si necesita ayuda constante, algo no está bien resuelto.",
    "principleAutonomyTitle": "🤲 Autonomía real",
    "principleEasyReadText": "Frases cortas, una idea por frase, vocabulario cotidiano. Cero tecnicismos en la interfaz que ve la persona usuaria.",
    "principleEasyReadTitle": "📖 Lectura Fácil",
    "principleNoPressureText": "Nada de cronómetros, ni \"game over\", ni puntuaciones negativas. El error se responde con ánimo y se puede reintentar sin límite.",
    "principleNoPressureTitle": "🚫 Sin presión",
    "principlePrivacyText": "Sin registro, sin cookies, sin analítica, sin cuentas. Todo el progreso se guarda únicamente en el dispositivo de la persona.",
    "principlePrivacyTitle": "🔒 Privacidad por defecto",
    "principleSoberTechText": "HTML, CSS y JavaScript sin frameworks. Funciona sin internet y se puede instalar como aplicación. Código abierto, en un repositorio público.",
    "principleSoberTechTitle": "🧱 Tecnología sobria",
    "principlesIntro": "Estas ideas están escritas primero en el código y después en los textos. Si una decisión las rompe, esa decisión está mal.",
    "principlesTitle": "Los principios que no negociamos",
    "routeNotice": "Esta página no se enlaza desde la aplicación. Solo se llega escribiendo la dirección.",
    "siblingCalculiaName": "Calculia",
    "siblingCalculiaText": "Cálculo y razonamiento lógico.",
    "siblingLinkHint": "Se abre en una pestaña nueva.",
    "siblingMemofunName": "Memofun",
    "siblingMemofunText": "Memoria y atención.",
    "siblingOkeymoneyName": "Okeymoney",
    "siblingOkeymoneyText": "Finanzas personales y autonomía cotidiana.",
    "siblingRoutimeName": "Routime",
    "siblingRoutimeText": "Rutinas y autonomía del día a día.",
    "siblingSinonimiaName": "Sinonimia",
    "siblingSinonimiaText": "Diccionario en lectura fácil.",
    "siblingsIntro": "Teclatlon es uno más de un pequeño grupo de proyectos hermanos: mismo equipo, misma filosofía de accesibilidad y sin servidor propio. Cada uno es un servicio independiente, con su propio dominio, al que se puede llegar desde aquí.",
    "siblingsTitle": "Proyectos hermanos",
    "tagline": "Una aplicación para la autonomía.",
    "techIntro1": "Teclatlon es una aplicación web instalable (PWA) compuesta por más de ",
    "techIntro2": ": la landing, el teclado virtual y rutas ocultas para familias, profesionales y mantenimiento.",
    "techIntroStrong": "5 páginas HTML estáticas",
    "techItem1Label": "Sin servidor propio",
    "techItem1Text": "es un conjunto de archivos servidos por un hosting estático. No hay backend, ni bases de datos, ni API propia.",
    "techItem2Label": "Funciona sin conexión",
    "techItem2Text": "una vez instalada, abre aunque no haya internet gracias al service worker y al caché local.",
    "techItem3Label": "Persistencia solo en",
    "techItem3Text": "el progreso (estrellas, letras practicadas, modo de teclado elegido) vive en el navegador del dispositivo. Nunca se envía a ningún sitio.",
    "techItem4Label": "Sin frameworks ni build step",
    "techItem4Text1": "JavaScript clásico compatible con navegadores antiguos y con el protocolo",
    "techItem4Text2": ". Pensado para que un técnico novel pueda leer y modificar una lección sin sorpresas.",
    "techItem5Label": "Código abierto (licencia MIT)",
    "techItem5Text": "cualquiera puede leerlo, auditarlo y proponer mejoras. Las decisiones de producto están escritas en este repositorio, no en presentaciones cerradas.",
    "techItem6Label": "Internacionalización desde el inicio",
    "techItem6Text": "cada texto vive en un archivo por idioma. Hoy Teclatlon está disponible en español de España e inglés.",
    "techItem7Label": "Dependencias externas: ninguna",
    "techItem7Text": ", excepto la descarga de las fuentes tipográficas Atkinson Hyperlegible y Nunito (usadas por su alta legibilidad).",
    "techTitle": "Cómo está hecha"
  }, "es");
})();
